version: '3'
services:
  nginx:
    image: repo.treescale.com/oleggromov/nginx-frontend:demo
    ports:
      - 80:80
    # the links should be explicitly set in order to work
    links:
      - pixel
      # - counter-demo
      # - ctr
    depends_on:
      - pixel
      # - counter-demo
      # - ctr

  pixel:
    image: repo.treescale.com/oleggromov/pixel:demo
    ports:
      - 3002:3002
    expose:
      - '3002'
    environment:
      NODE_ENV: production

  # counter-demo:
  #   image: repo.treescale.com/oleggromov/counter-app:0.3
  #   expose:
  #     - '3000'
  #   env_file:
  #     - secrets/counter.env
  #     - secrets/counter-demo.env
  #   environment:
  #     NODE_ENV: production
  #   depends_on:
  #     - mysql

  # ctr:
  #   image: repo.treescale.com/oleggromov/counter-app:0.3
  #   expose:
  #     - '3000'
  #   env_file:
  #     - secrets/counter.env
  #     - secrets/counter-live.env
  #   environment:
  #     NODE_ENV: production
  #   depends_on:
  #     - mysql

  # mysql:
  #   image: repo.treescale.com/oleggromov/counter-mysql:0.5
  #   expose:
  #     - '3306'
  #   env_file:
  #     - secrets/counter.env
  #     - secrets/counter-mysql.env
  #   volumes:
  #     - ~/counter-mysql-data:/var/lib/mysql
