version: '3'
services:
  nginx:
    image: repo.treescale.com/oleggromov/nginx-frontend:0.4
    ports:
      - 80:80
    # the links should be explicitly set in order to work
    links:
      - counter-demo
      - ctr
    depends_on:
      - counter-demo
      - ctr

  counter-demo:
    image: repo.treescale.com/oleggromov/counter-app:0.3
    expose:
      - '3000'
    env_file:
      - secrets/counter.env
      - secrets/counter-demo.env
    environment:
      NODE_ENV: production
    depends_on:
      - mysql

  ctr:
    image: repo.treescale.com/oleggromov/counter-app:0.3
    expose:
      - '3000'
    env_file:
      - secrets/counter.env
      - secrets/counter-live.env
    environment:
      NODE_ENV: production
    depends_on:
      - mysql

  mysql:
    image: repo.treescale.com/oleggromov/counter-mysql:0.4
    expose:
      - '3306'
    env_file:
      - secrets/counter.env
      - secrets/counter-mysql.env
    volumes:
      - ~/counter-mysql-data:/var/lib/mysql
